### ISSUE TITLE
dbSize 和 pexpire 命令在行为上与官方服务端不一致

### ISSUE THREAD

**Issue by LamGC** [microwww/jedis-mock#1]
`dbSize` 命令在数据库为空的情况下依然返回`16`（Linux: `0`, Windows: `0`）命令：`dbsize`
`pexpire`命令在指定key不存在的情况下依然返回`1`（Linux: `0`, Windows: `0`）命令：`pexpire test 500`
对比服务端版本为：
- Windows: 3.0.504
- Linux: (docker) redis:3-alpine3.8  |  3.2.12

出现问题的版本：`0.1.0-3.0`

**Comment by LamGC** [comment]
对比过程中所使用的Windows版本Redis：
[Redis-x64-3.0.504.zip](https://github.com/microwww/jedis-mock/files/5177673/Redis-x64-3.0.504.zip)

**Comment by lichangshu** [comment]
> `dbSize` 命令在数据库为空的情况下依然返回`16`（Linux: `0`, Windows: `0`）命令：`dbsize`
> `pexpire`命令在指定key不存在的情况下依然返回`1`（Linux: `0`, Windows: `0`）命令：`pexpire test 500`
> 对比服务端版本为：
> 
> * Windows: 3.0.504
> * Linux: (docker) redis:3-alpine3.8  |  3.2.12
> 
> 出现问题的版本：`0.1.0-3.0`

谢谢 我最近会修复一下
